### ISSUE TITLE
Standalone embedded charts don't render in iframes

### ISSUE THREAD

**Issue by etr2460** [apache/superset#12612]
When embedding a chart in an iframe with the `standalone=true` param, it doesn't render

### Expected results
See the full chart with no sidebar

### Actual results
See nothing

#### How to reproduce the bug

1. Click the embed button for a chart in explore
2. Copy the iframe code and put on a webpage
3. See nothing

### Environment

- superset version: `master`

### Additional context
Note that the whole page renders when used in an iframe, so this only happens when the standalone param is used. I suspect it was caused by the new sidebar added to explore or one of the other redesigns.

cc @zuzana-vej

**Comment by junlincc** [comment]
related: https://github.com/apache/superset/issues/12557

**Comment by dpgaspar** [comment]
@etr2460 can you check that this was fixed with: https://github.com/apache/superset/pull/12606 ?

**Comment by etr2460** [comment]
Will verify after today's release, thanks!

**Comment by etr2460** [comment]
Yup, this fixed it. Thanks!

**Comment by zhangfeng114** [comment]
@etr2460 

I used the upgrade command to upgrade to the latest version, but this problem still occurs, how did you solve it? 
`pip install apache-superset --upgrade`
`superset db upgrade`
`superset init`

thanks
