### ISSUE TITLE
[Explore] Server pagination is not working

### ISSUE THREAD

**Issue by RossMoir** [apache/superset#15478]
Server side pagination has no effect. The server side pagination option for the table chart correctly retrieves the first page of results but the page jumps will not respond to inputs. Issue #14727 shows similar experiences but was closed however the effect remains in Superset `1.2`.

### Expected results

On new page selection the next 10 results should be shown.

### Actual results

On new page selection the table stays on the first page and no new queries are conducted.

https://user-images.githubusercontent.com/44472119/123997942-d7ac1e00-d9c8-11eb-93ac-ea5ded370b7d.mov

#### How to reproduce the bug

1. Launch Superset 1.2 with a connected Apache Druid 0.21.1 database.
2. Create a Table from the Druid dataset.
3. Enable 'Server Pagination'

### Environment

(please complete the following information):

- superset version: `1.2`
- druid version: `0.21.1`

**Comment by junlincc** [comment]
This issue has been fixed, however... it introduce a new issue - the pagination disappear entirely.... @jinghua-qa please double check 🙏

https://user-images.githubusercontent.com/67837651/124046859-bf87cf00-d9c7-11eb-8f8e-101c0cfcac25.mov

**Comment by aelich** [comment]
Hi guys 

I have the same issue just with postgres DB, any hint how to fix, please?

**Comment by junlincc** [comment]
verify fixed on master @aelich @RossMoir 
https://user-images.githubusercontent.com/67837651/125526154-5676e608-d100-4485-837b-7ad2fed61aa0.mov

**Comment by RossMoir** [comment]
@junlincc Trying this out on master it is still broken. Your video doesn't have 'Server Pagination' enabled, notice the number of rows and the option on the left is disabled, this means only a single query is made not a new one for each page flip. Please reopen this issue as it remains broken. @aelich can you confirm?

https://user-images.githubusercontent.com/44472119/125602810-3e2c065e-f255-4f81-866f-abb99403b641.mov

**Comment by aelich** [comment]
@junlincc please don’t close its still broken, just tried it. (When you don't click on server pagination, like you have shown in last video, superset makes one big query and transfer all the data at once so when you click on buttons its just pagination and data is already in browser...)

@RossMoir I totally support you and confirmed it, its still broken i tried master branch on mysql and postgres few min ago its still broken!

For my case this is very relevant features so if can fix if would be amazing.

**Comment by RossMoir** [comment]
> For my case this is very relevant features so if can fix if would be amazing.

Completely agree, this is high priority for our use case. Any use of larger queries benefit greatly from server-side pagination and a fix would be extremely appreciated.

**Comment by aelich** [comment]
@RossMoir  I think we need to make one more issue, I dont think this one will re-open this one again, can you please make it (as I dont have videos) and i'll support you on new issue.
