### ISSUE TITLE
deck.gl Scatterplot NaN legend for TEXT/STRING column

### ISSUE THREAD

**Issue by mona-mk** [apache/superset#15738]
Legend is shown as NaN in deck.gl scatter plot when TEXT or STRING column data type is selected as point color.
<img width="589" alt="Screenshot 2021-07-16 at 11 12 50" src="https://user-images.githubusercontent.com/59080347/125915292-ca1664db-c776-4683-9097-5a3fe811435b.png">

1. Geneate a deck.gl plot
2. Under point color, pick a TEXT or STRING column
3. See NaN as legend

Environment:
- superset version: `1.2.0`

**Comment by fcomuniz** [comment]
Same issue here

**Comment by colorzhang** [comment]
tried today. same issue.

**Comment by villebro** [comment]
Would it be possible to add some more context? (redacted of course)
- Screenshots of the Explore view, especially the critical parts of the control panel
- Screenshots of the data panel (both results and samples)
- Expected result in the legend based on the data based on what's visible in the screenshots

Point being, by making the problem as easy to reproduce as possible, the community can focus developer time on working on the fix as opposed to reproducing the bug.

**Comment by mona-mk** [comment]
Thanks Ville. Further (easier) description on how to reproduce:

1. Open `deck.gl Demo` dashboard
2. On `Scatterplot` demo, click on three vertical dots on the right corner and select `View chart in Explore`
3. Under point color, select a TEXT dimension (in screen shot I randomly picked `STREET`)
4. You will see NaN in legend

Of course this is a dummy example, but hopefully will clarify the problem. Please see the requested screen shots enclosed. Expected result in this case is seeing the street names in legend, i.e. based on Data screen shot:

- Fulton Street 
- Mason Street 
- Hyde Street
- ....
Also, changing the formatting to `Original value` doesn't help.

<img width="1915" alt="Screenshot 2021-08-19 at 9 31 45" src="https://user-images.githubusercontent.com/59080347/130019353-111c2559-5912-4332-ac2e-8a97a54116c9.png">
<img width="1284" alt="Screenshot 2021-08-19 at 9 33 09" src="https://user-images.githubusercontent.com/59080347/130019513-2c53ac1d-1754-404d-ab08-f226b454413b.png">

**Comment by villebro** [comment]
Hi @mona-mk , I was able to reproduce and was able to come up with a quick fix (I also fixed the broken tooltip at the same time):
![image](https://user-images.githubusercontent.com/33317356/130038317-74e11084-3609-4805-a101-5a9f73ae90a3.png)

I'll clean up the PR and open it in a sec

**Comment by villebro** [comment]
@mona-mk here's the fix PR: https://github.com/apache-superset/superset-ui-plugins-deckgl/pull/43

**Comment by villebro** [comment]
@mona-mk @fcomuniz @colorzhang this is now fixed on master, feel free to try it out at your convenience

**Comment by fcomuniz** [comment]
thanks!

**Comment by mona-mk** [comment]
Thanks you very much Ville! Just pulled the `latest-dev` image and tested. Confirm it works as it should.

**Comment by Deninc** [comment]
> @mona-mk @fcomuniz @colorzhang this is now fixed on master, feel free to try it out at your convenience

How do I check when this is merged into the official release?

**Comment by mona-mk** [comment]
@villebro today I pulled `1.3.0` and `1.3.1` images, and I still have this bug. Isn't it already included in one of the official releases?

**Comment by villebro** [comment]
@mona-mk unfortunately due to our current multirepo setup, it's very difficult to cherrypick viz plugin fixes into official Apache releases after a release branch has been cut. But we should be cutting the 1.4 branch very soon, so if you can wait just a little while longer it will be included in an official release.

**Comment by MichaelTiemannOSC** [comment]
Just hit this myself.
