### ISSUE TITLE
[welcome page][perf] Slow queries to generate welcome page

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#16528]
#### How to reproduce the bug

0. As user using Superset for years, 
1. Go to https://superset.d.musta.ch/superset/welcome/
2. Welcome page show spinner very, very long time:
![kpFvNcc17A](https://user-images.githubusercontent.com/27990562/131545199-87ef745f-04a4-41e2-ac95-e269d7f93696.gif)
3. from MySQL Slow query log, I can see the query to get recent viewed items can take > 20 mins.

### Environment

airbnb production

- superset version: `superset version`: latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cesar-loadsmart** [comment]
We saw that some of the queries used to fill out the welcome page access the `logs` table at the metadata DB. 
In our case, this table didn't have an index. In other words, it's fine for test environments, but as Superset grows in your company this might became a problem:


![image](https://user-images.githubusercontent.com/89807801/186500083-d691beca-d85d-4503-82bf-3ff58cf8aa44.png)

**Comment by D3nn3** [comment]
Can confirm this. Saw the same query in our Postgres DB logs taking almost 10s.

**Comment by cesar-loadsmart** [comment]
We've fixed our problem by creating a specific index for this query:
```
SELECT anon_1.dashboard_id AS anon_1_dashboard_id, anon_1.slice_id AS anon_1_slice_id, anon_1.action AS anon_1_action, anon_1.dttm AS anon_1_dttm, dashboards.slug AS dashboard_slug, dashboards.dashboard_title AS dashboards_dashboard_title, slices.slice_name AS slices_slice_name 
FROM (SELECT logs.dashboard_id AS dashboard_id, logs.slice_id AS slice_id, logs.action AS action, max(logs.dttm) AS dttm 
FROM logs 
WHERE logs.action IN ('explore', 'dashboard') AND logs.user_id = <USERID> AND logs.dttm > '2021-08-24T17:20:50.496891'::timestamp AND (logs.dashboard_id IS NOT NULL OR logs.slice_id IS NOT NULL) GROUP BY logs.dashboard_id, logs.slice_id, logs.action) AS anon_1 LEFT OUTER JOIN dashboards ON dashboards.id = anon_1.dashboard_id LEFT OUTER JOIN slices ON slices.id = anon_1.slice_id 
WHERE dashboards.dashboard_title != '' OR slices.slice_name != '' ORDER BY anon_1.dttm DESC 
 LIMIT 6
```

Our Superset became faster than it was released, today we have around 400 users and more than 100 published dashboards.

**Comment by chathawee** [comment]
> We've fixed our problem by creating a specific index for this query:
> 
> ```
> SELECT anon_1.dashboard_id AS anon_1_dashboard_id, anon_1.slice_id AS anon_1_slice_id, anon_1.action AS anon_1_action, anon_1.dttm AS anon_1_dttm, dashboards.slug AS dashboard_slug, dashboards.dashboard_title AS dashboards_dashboard_title, slices.slice_name AS slices_slice_name 
> FROM (SELECT logs.dashboard_id AS dashboard_id, logs.slice_id AS slice_id, logs.action AS action, max(logs.dttm) AS dttm 
> FROM logs 
> WHERE logs.action IN ('explore', 'dashboard') AND logs.user_id = <USERID> AND logs.dttm > '2021-08-24T17:20:50.496891'::timestamp AND (logs.dashboard_id IS NOT NULL OR logs.slice_id IS NOT NULL) GROUP BY logs.dashboard_id, logs.slice_id, logs.action) AS anon_1 LEFT OUTER JOIN dashboards ON dashboards.id = anon_1.dashboard_id LEFT OUTER JOIN slices ON slices.id = anon_1.slice_id 
> WHERE dashboards.dashboard_title != '' OR slices.slice_name != '' ORDER BY anon_1.dttm DESC 
>  LIMIT 6
> ```
> 
> Our Superset became faster than it was released, today we have around 400 users and more than 100 published dashboards.

Hi @cesar-loadsmart Could you please provide the statement to create the Index? Right now, we are facing this issue also. Could you please provide me the create statement? Thanks in advance.

**Comment by cesar-loadsmart** [comment]
Hi @chathawee, I believe these two indexes can help you:

`CREATE INDEX logs_user_id_dttm_idx ON public.logs USING btree (user_id, dttm)`

and 

`CREATE INDEX logs_user_id_dttm_idx1 ON public.logs USING btree (user_id, dttm) WHERE (((action)::text = ANY ((ARRAY['explore'::character varying, 'dashboard'::character varying])::text[])) AND ((dashboard_id IS NOT NULL) OR (slice_id IS NOT NULL)))`

Please test them and let me know.

**Comment by chathawee** [comment]
> 

Cheers!

**Comment by D3nn3** [comment]
This is still a problem and all PR tackling this issue (#20636 and #21873) have been closed. Are there any plans to properly fix the underlying issue here?

**Comment by rusackas** [comment]
Is anyone still facing this? It's been quiet for quite a long time. CC @john-bodley to see if the original reporting org has metrics here.

**Comment by D3nn3** [comment]
Can still reproduce this with 3.1 @rusackas 

We didn't try some of the proposed fixes (e.g. creating an index for specific tables), so this is from a vanilla instance (but upgraded from v1 -> v2 -> v3 and not a fresh install of Superset v3).

![image](https://github.com/apache/superset/assets/20516965/db131ac5-1da9-4f75-b886-1a7ebf8fc8f8)

**Comment by michael-s-molina** [comment]
Thank you for reporting this issue. However, the issue was reported on a version of Superset that we no longer support or it does not contain a valid Superset version. As of this moment, we only actively support Superset 4.0 and 4.1. To maintain a more actionable Issues backlog, we're going to close this issue for now. If you (or anyone reading this) are still experiencing this on a currently supported version of Superset, please either reopen this Issue, or file a new one with updated context (screenshots, reproduction steps) and we'll do our best to support it. Thank you
