### ISSUE TITLE
Curb the automatic query generation from superset for clickhouse

### ISSUE THREAD

**Issue by mayank-pant** [apache/superset#19690]
### Motivation

Different databases have different ways to optimize query. There are some changes which are forced from superset side which inhibits the query performance at the back end. One such optimization for clickhouse i have identified.

### Proposed Change

Currently in bar-chart even when you have not selected LIMIT. LIMIT 50000[max value] still appears in the final query. If a table being queried uses projection(similar to indexes) in DB then clickhouse query optimizer gives inconsistent/wrong result for the query when using both LIMIT and ORDER BY in query. 
I propose that if we do not select limit from the GUI, then it should not appear automatically in the final query.

Attached github links to ongoing issue with projection and order by and limit in clickhouse.
(https://githubhot.com/repo/ClickHouse/ClickHouse/issues/35701)
(https://github.com/ClickHouse/ClickHouse/issues/32943)

### New or Changed Public Interfaces

I dont have much idea about internals of superset but i have described my problem above.

### New dependencies

n.a

### Migration Plan and Compatibility

n.a

### Rejected Alternatives

n.a

**Comment by srinify** [comment]
This is great Mayank, thanks for opening this! I removed the "SIP" pre-fix, because that's reserved for big system level changes to Superset that needs lots of discussion and buy-in. This feels more like a database specific optimization & polish, which is awesome

**Comment by villebro** [comment]
@mayank-pant thanks for raising this issue. Did I understand correctly that this is something that's being worked on, i.e. might get fixed at some point? Or is this "a feature, not a bug"? There's a few solutions that we can consider, but I'd like to understand more about the underlying issue before going ahead with a fix..

**Comment by mayank-pant** [comment]
I dont have idea if this is bug or a feature, author of projection was not clear on this part. But i am saying generally if we do not select any value in limit drop down, superset should not add limit to the query automatically. Sorry for the late reply !!

**Comment by mayank-pant** [comment]
I dont have idea if this is bug or a feature, author of projection was not clear on this part. But i am saying generally if we do not select any value in limit drop down, superset should not add limit to the query automatically. Pls ignore closed comment above, hastily clicked on the button

**Comment by mayank-pant** [comment]
Pls let me know if anyone will be working on this issue and any timeline will be appreciated.

**Comment by rusackas** [comment]
I don't think this is being worked on... but maybe someone (@villebro?) can validate that this is still an issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
