### ISSUE TITLE
Other admin users can't see "saved queries" created by another admin users

### ISSUE THREAD

**Issue by winglight** [apache/superset#20604]
#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Click on 'Saved queries'
3. No items in the list

### Expected results

Show the list of all saved queries despite of creators

### Actual results

Only queries created by the current user can be shown in the list

### Environment

(please complete the following information):

- browser type and version: chrome on win11
- superset version: `commit 16654034849505109b638fd2a784dfb377238a0e`
- python version: `3.8.12`
- node.js version: `none`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [*] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [*] I have reproduced the issue with at least the latest released version of superset.
- [*] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

My superset runs on a docker container by docker-compose.

**Comment by emilija-omnisend** [comment]
Hello. Any news? We're trying to track our table references in Superset and this is the only part left.

**Comment by pengwk** [comment]
This can temporarily solve the problem @emilija-omnisend @winglight 
```
diff --git a/superset/queries/saved_queries/filters.py b/superset/queries/saved_queries/filters.py
index c53ff5619..a0f6f2fb9 100644
--- a/superset/queries/saved_queries/filters.py
+++ b/superset/queries/saved_queries/filters.py
@@ -65,6 +65,4 @@ class SavedQueryFilter(BaseFilter):  # pylint: disable=too-few-public-methods

         :returns: flask-sqlalchemy query
         """
-        return query.filter(
-            SavedQuery.created_by == g.user  # pylint: disable=comparison-with-callable
-        )
+        return query
```

**Comment by Bill0412** [comment]
I think this should be merged, otherwise the share link functionality is meaningless.

**Comment by eschutho** [comment]
We are planning to add UUID query lookup support in the near future to fix this problem. There should be a fix in 3.0.

**Comment by rusackas** [comment]
@eschutho do you know if that work transpired and this was just never closed?

**Comment by eschutho** [comment]
> @eschutho do you know if that work transpired and this was just never closed?

@rusackas No we haven't had a chance to work on this. I think we should try to get the proposed PR merged instead.

**Comment by rusackas** [comment]
Is anyone here willing to open the proposed PR? If not, this will likely be closed soon as stale/inactive/not-planned.

**Comment by SamraHanifCareem** [comment]
We are planning to work on implementing this workflow. Similar to what we have for datasets and other screen.
There should be multiple owners for each query; able to make updated

**Comment by YaqoobAlam** [comment]
We have deployed latest Superset version 4.1.2 and we are facing this same issue. Only the creator of the saved queries can see when a user click on a saved query link from another person they will see a new SQL lab editor and an error "The query couldn't be loaded".  When we looked into the Superset DB we can see all the queries have the owners. Till the resolution of this is there a way we can add multiple users so that they can see the same query and nothing breaks. Below are our saved_query table for now.

 id |                                      label                                      | created_by_fk | user_id 
----+---------------------------------------------------------------------------------+---------------+---------
  1 | Stage Incidents V2                                                              |             5 |       5
  2 | Activity_incidents                                                              |             5 |       5
  7 | SFA_Revenue Detail Weekly                                                       |             7 |       7
  9 | SFA_Revenue Detail Monthly (MRR)                                                |             7 |       7
 21 | Motaz Task II                                                                   |            16 |      16
 10 | SFA_Operations Detail Weekly                                                    |             7 |       7
 11 | finding_which_classroom_attended_session                                        |             8 |       8
 13 | Calls RD                                                                        |            16 |      16
 14 | Telesales Leads N2                                                              |            16 |      16
 15 | Calls Dashboard                                                                 |            16 |      16
 16 | Potential Students                                                              |            16 |      16
 18 | N2 Transactions RD                                                              |            16 |      16
 20 | RFM RD                                                                          |            16 |      16
 23 | Counting # Sessions by time buckets                                             |            19 |      19
 25 | Blocked and reported students query                                             |            19 |      19
 26 | App Sessions with B2B attendees                                                 |            19 |      19
 28 | CALLED                                                                          |            13 |      13
 31 | new_practise_aggregate                                                          |            13 |      13
 29 | Transaction                                                                     |            13 |      13
 27 | LEADS                                                                           |            13 |      13
 30 | test                                                                            |            14 |      14
 32 | new_raw_practice_data                                                           |            13 |      13
 33 | 2025-07-15 - activity incidents (removed survey temps)                          |             5 |       5
 34 | Yaqoob-test-query                                                               |             3 |       3

**Comment by rusackas** [comment]
There's some discussion about this happening:
* Should Admins only be able to SEE the saved queries, or should they have the ability to edit/delete them too?
* Should this actually be allowed? Can your Google Docs admin see all the org's Google Docs?

Definitely useful when a user leaves an org and someone needs to "adopt" leftover assets... but the user groups feature should cover that part (just add the old user to a team, and anyone on that team can have access)

**Comment by rusackas** [comment]
This might also get overwhelming for admins of larger orgs where they might see hundreds of thousands of queries all of a sudden.

Another approach might be to make it so you can re-assign a user's assets (doesn't fix all use cases) but what you're proposing here DOES fit the model of other Superset assets... Admins just need to be careful about deleting other people's things.

Adding the concept of "owners" for saved queries is also of interest to @justinpark @michael-s-molina so you can just add users (effectively sharing it).

**Comment by rusackas** [comment]
Maybe @dpgaspar can enlighten us on the state of the User Groups SIP work. Not sure if it's ready for prime time or not.

**Comment by rusackas** [comment]
This issue has been open for over three years and the proposed fix in the thread has not been turned into a PR. A contributor (@SamraHanifCareem) expressed intent to work on it, but nothing has landed yet.

We're open to input, PRs, or a SIP on the right approach. The tradeoffs are non-trivial — options include: (1) allowing admins to see all saved queries globally, (2) adding an "owners" model to saved queries (similar to charts/dashboards), or (3) leveraging the User Groups work to enable sharing. If you're interested in contributing, please comment here with your proposed approach before writing code, so maintainers can align on the direction.

**Comment by pengwk** [comment]
Quick update here: I picked this back up in apache/superset#21769 and pushed the latest changes.

Based on the discussion above, especially the questions around whether admins should only be able to see saved queries or also edit/delete them, the PR now takes the narrower approach:

- Users with `all_query_access` can see/read saved queries created by other users.
- Write paths still keep the ownership filter, so `all_query_access` does not allow bulk-deleting another user’s saved query.
- This avoids turning saved queries into a full shared ownership model in this PR. Owners/User Groups still seem like the better long-term direction for true sharing or asset adoption workflows.

I also kept the UX concerns in mind:
- The Saved Queries list includes a `Created by` column.
- There is a `Created by` filter, so admins who can see more queries can still narrow the list.
- The existing search/filtering behavior remains available.

Latest PR changes:
- Rebased onto current `master`.
- Added toast handling for `created_by` related-field fetch errors.
- Cleaned up the export command tests by mocking `can_access_all_queries()` directly.
- Added an integration test confirming that `all_query_access` does not bypass ownership for bulk delete.
- Addressed minor bot style comments around frontend typing and test type annotations.

Local verification:
- Saved query API + command integration tests: `44 passed`
- Changed-file `pre-commit` passed, including frontend type-check, ruff, and pylint.

Thanks everyone for the thoughtful discussion and for keeping this issue alive. I hope this scoped version is a reasonable step forward while leaving the larger owners/User Groups sharing model for a follow-up.
