### ISSUE TITLE
[Dashboard] Issue with tabbed dashboard

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#20930]
There are 2 issues:
1. When user leaves dashboard on any tab other than the 1st tab, that tab is seen selected when user returns to dashboard. Even though the charts from 1st tab are visible.
2. In first situation, if user clicks on 1st tab and then again to previous tab, the chart data loading gets stuck.

#### How to reproduce the bug

1. Open Sample Dashboard, 'Sales Dashboard'.
2. Go to 'Exploratory' tab
3. Go to 'Dashboards' list page
4. Again, open 'Sales Dashboard'
5. 1st issue
6. Click on 'Sales Overview' tab
7. Click on 'Exploratory' tab
8. 2nd issue

### Expected results

1st issue: Dashboard opens with charts from 1st tab, and 1st tab seen selected.
2nd issue: Dashboard should load the charts normally.

### Actual results

1st issue: Dashboard open with charts from 1st tab, but 2nd tab is seen as selected.
2nd issue: Dashboard cannot load data in the charts.

#### Screenshots
![dashboard_tab](https://user-images.githubusercontent.com/74634977/182101218-baca5e8d-9277-43b9-a7e4-831beee6b40a.gif)

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `2.0.0`
- Docker image
- any feature flags active: DASHBOARD_NATIVE_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It is possible that both issues are related, solving 1st may resolve 2nd also.

**Comment by sfirke** [comment]
I can replicate both of these problems in Firefox with Superset 2.0.0.  The second problem, chart data loading getting stuck, is the bigger problem for me.

In my case, it's a dashboard with native filters that only apply to the third of three tabs.  When the page loads for the public, the charts are stuck on the loading animation.  Clicking between the 1st and 2nd tabs doesn't get the charts to load, they only load when I click the 3rd tab.  Then charts load on all tabs after that.

**Comment by mdeshmu** [comment]
We want to upgrade to 2.0.1 but fear that it will impact our production users if this is broken in 2.0.0. A fix will be really appreciated.

**Comment by eschutho** [comment]
I tested the first issue and couldn't replicate it on the [2.0.1 test environment](http://52.41.29.59:8080/). Can someone else verify that this was fixed?

**Comment by kamalkeshavani-aiinside** [comment]
@eschutho I checked, and could reproduce both issues on 2 different dashboards with tabs.

**Comment by stephenLYZ** [comment]
@kamalkeshavani-aiinside I'm not sure. I have try to reproduce but I can't. It's wired.

https://user-images.githubusercontent.com/11830681/201142500-60c85a82-5fe4-4304-8def-c649eae8c5c5.mov

**Comment by sfirke** [comment]
The issue with a dashboard's first tab not loading until a different tab is clicked on persists on 2.0.1rc2.  It hangs like this indefinitely until I click the "Violations" tab:
![image](https://user-images.githubusercontent.com/7569808/201149555-245e9e7d-135e-41c1-b33e-036c03328dce.png)

**Comment by kamalkeshavani-aiinside** [comment]
@stephenLYZ Did you try the Docker Hub image or docker-compose. I am able to reproduce the issue with the Docker Hub image.(haven't tried docker-compose)
The reason why I ask is that the dashboard owner [issue](https://apache-superset.slack.com/archives/CH307T4JG/p1667337331406779) reported in rc2, is not reproducing with the docker hub image somehow.

**Comment by hushaoqing** [comment]
I tested it based on the master branch, It has been fixed.

@stephenLYZ Could you help with this issue? https://github.com/apache/superset/issues/22062

**Comment by sfirke** [comment]
> @stephenLYZ Did you try the Docker Hub image or docker-compose. I am able to reproduce the issue with the Docker Hub image.(haven't tried docker-compose) The reason why I ask is that the dashboard owner [issue](https://apache-superset.slack.com/archives/CH307T4JG/p1667337331406779) reported in rc2, is not reproducing with the docker hub image somehow.

I don't follow how this is "Docker Hub **or** docker-compose" ... I'm running the command `docker-compose up` to deploy, using the 2.0.1rc2 image from Docker Hub at https://hub.docker.com/r/apache/superset/tags?page=1&name=2.0.1rc2 (and this bug persists)

**Comment by sfirke** [comment]
If anyone needs an example for debugging this issue, see this public-facing dashboard: https://analytics.a2gov.org/superset/dashboard/traffic-crashes/  It will hang until the user clicks "Filters out of scope" / clicks through other tabs / reloads the dashboard.

I have at least one other dashboard that replicates this bug.  As well as several tabbed dashboards with "filters out of scope" that _don't_ have this behavior.  I'm happy to meet and screenshare/show this behavior if it would be helpful for debugging.

**Comment by sfirke** [comment]
@kamalkeshavani-aiinside - I think I've isolated the cause of the dashboard not loading behavior, it appears when "Select first filter value by default" box is checked on the out-of-scope filter.  When I uncheck that box then the dashboard loads properly.  Can you confirm this with one of your dashboards?

I'm able to make this bug appear/disappear on both my production dashboards in 2.0.1 and example data dashboards in 2.1.0rc1 by checking/unchecking this box.

**Comment by eschutho** [comment]
This should be fixed in 2.1 with this PR: https://github.com/apache/superset/pull/23299. Closing this issue for now.
