### ISSUE TITLE
plugin-chart-table: Chart looses customization on save

### ISSUE THREAD

**Issue by mayurnewase** [apache/superset#21502]
When table chart is saved with conditional formatting, it reloads the page without those customizations.
But after reloading it again correctly sets the customizations.

#### How to reproduce the bug
1. create table chart on any data
2. in customize tab, add conditional formatting on any column
3. click on save
4. see colors disappear
5. reload the page again, should show colors in the cell correctly.

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots

[Screencast from 17-09-22 03:07:57 PM IST.webm](https://user-images.githubusercontent.com/12967587/190850542-ab40f4d3-01f9-470f-8b34-6a90681131b7.webm)

### Environment

(please complete the following information):

- browser type and version: crome
- superset version:  latest master (last commit sha: 8c16806f5759ecc53ecef88a2e96e2e0964bffc6)
- python version: 3.9
- node.js version: 16.13.1
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Always-prog** [comment]
Hello @mayurnewase! 
Do Superset have any updates on this problem? I'll try to fix it.

**Comment by Shazad-khan** [comment]
![image](https://user-images.githubusercontent.com/100838455/225651207-512a9dc8-f64d-47fe-be50-6d631225e53b.png)

This issue has been fixed please close this issue

**Comment by Always-prog** [comment]
@Shazad-khan Hello.
Can you share commit/PR with fix of this issue please?

**Comment by Shazad-khan** [comment]
i haven't fixed it i just tested this issue in the latest version and i haven't found any issue.

**Comment by Always-prog** [comment]
Strange, I tested the latest version of Superset and bug is still exists.
