### ISSUE TITLE
Schema name is needed for Dataset in UI but not in API

### ISSUE THREAD

**Issue by dreseldo** [apache/superset#21768]
When creating a dataset the schema field must be filled out. If the database does not support schemas (like SolR) the dataset cannot be created because the list of tables gets not filled. When using the API call for creating a dataset the schema string may be empty. If a datasource is created via the API the dataset works well and is delivering data. However it cannot be edited via the UI because of the empty schema field.

This was all tested by using a modified sqlalchemy-solr driver which has the method "get_schema_names" removed (I saw that in the superset source code it is checked if this method exists and if it does not exist an empty array is returned). The method was removed because if the original method is left in, the SQL queries fail in superset because it attaches the 'default' schema to the SolR queries which does not make sense. So basically the queries in superset work without a schema.

#### How to reproduce the bug

1) Post the API: curl 'https://dns:port/api/v1/dataset/' with {"database": xxxxx, "schema":"", "table_name": "yyyy"}
-> Dataset will be created with a null schema
2) Try to create a dataset without schema in the UI
-> Will not work

### Expected results

I am able to enter some sort of value into the schema drop down which is interpreted as "no schema support". After that the tables of the database are listed and I can select one of it

### Actual results

When I am using the unpatched sqlalchemy-solr driver, I can select the 'default' entry as schema in the UI and are able to create the dataset. However queries in this dataset fail because the non-existing schema is inserted into the sql command (like SELECT ... from `default`.`table01`. When using the patched sqlalchemy-driver (without the get_schema_names method) I get stuck at the input box for the schema and I have to add the dataset via the API with empty schema.

#### Screenshots
Dataset with default schema provided by the sqlalchemy_solr driver:
![dataset_with_default_schema](https://user-images.githubusercontent.com/115547943/195082658-dbe769c0-0d1d-4837-b88d-bffeca9aec21.png)
Resulting sql error when using the default schema:
![dataset_with_default_schema_exc](https://user-images.githubusercontent.com/115547943/195082678-e0a82e9f-090e-417f-8fbd-c563067a7525.png)
Trying to edit the dataset which was created via API with empty schema:
![dataset_edit_without_schema](https://user-images.githubusercontent.com/115547943/195082687-201e10bd-9cc3-4230-aaa3-6b5718b9099a.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 106.0.5249.103 (Official Build) (64-bit)
- superset version: 2.0.0
- python version: 3.9.2
- node.js version: not installed (no node binary)
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any -> See images
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

If there is more information needed do not hesitate to contact me :-) Thanks!

**Comment by robson-koji** [comment]
I went to the same problem, and as discussed in Slack there is already a fix for this. 

You need to change  superset_config.py and create a SQL_QUERY_MUTATOR function like this:

```
def SQL_QUERY_MUTATOR(sql: str, **kwargs: Any) -> str:
    return sql.replace("`default`.", "")
```

**Comment by rusackas** [comment]
Can we call this case closed, or do we need a documentation addition somewhere?

**Comment by aadel** [comment]
This issue occurs when using `sqlalchemy_solr` driver release < `0.2.3` with a recent Superset release, like 2.x or newer. It has been resolved with the driver release `0.2.3` which handles schema in queries through SQLAlchemy interpreter.

**Comment by rusackas** [comment]
I'm assuming from the silence that this isn't really an issue anymore. People should be installing a more current version of sqlalchemy_solr, I suppose... if you think that needs to be mentioned in the docs, we would welcome a documentation PR. Otherwise, it doesn't sound like we have a Superset bug remaining, so I'll optimistically close this. Happy to revisit/reopen if warranted.
