### ISSUE TITLE
Only some links are not on https [Traefik + Letsencrypt + Docker-compose]

### ISSUE THREAD

**Issue by w4rell** [apache/superset#24174]
Hi there,

I searched around the whole internet about using a reverse-proxy with Superset and I'm still blocked with this issue.
I can't create new dashboards from the button, it's responding in HTTP instead of HTTPS, everywhere else my Traefik is working properly.

#### Cases where it works
1. Go to URL for login without HTTPS
2. It redirects to HTTPS and I can continue

#### How to reproduce the bug

1. Click on +DASHBOARD
2. Now it shows : 404 page not found
3. The URL is : http://superset.instance/dashboard/new/
4. If I change to HTTPS manually, it works

### Expected results

Use persistant HTTPS instead of rewriting in HTTP.

### Actual results
Goes to HTTP.

### Environment

I'm using the docker compose image.
- browser type and version:  ̀Firefox 113.0.1 (64bits)/Opera 98.0.4759.15`
- os : `Ubuntu 22.04`
- superset version: `0.0.0 (latest)`
- python version: `Python 3.9.16`
- node.js version: `Last`
- traefik version : `2.9`

docker-compose-non-dev.yml :
```
services:
  traefik:
    image: "traefik:v2.9"
    container_name: traefik
    hostname: traefik
    command:
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.scheme=websecure
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api
      - --certificatesresolvers.le.acme.email=mail@mail.eu
      - --certificatesresolvers.le.acme.storage=./acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme/acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.superset.rule=Host(`superset.instance`)"
      - "traefik.http.routers.superset.service=superset"
      - "traefik.http.routers.superset.entrypoints=websecure"
      - "traefik.http.routers.superset.tls=true"
      - "traefik.http.routers.superset.tls.certresolver=le"
      - "traefik.http.services.superset.loadbalancer.server.port=8088"
    depends_on: *superset-depends-on
    volumes: *superset-volumes
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ X ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X ] I have reproduced the issue with at least the latest released version of superset.
- [ X ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I've also tested everything related to these lines in superset/config.py: 

```
ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 1, "x_prefix": 1}
PREFERRED_URL_SCHEME = 'https'
``̀`

Thanks again for your help !

**Comment by Raymanrrr** [comment]
I guess the redirect response caused this, my superset:2.1.0 also encounters add dashboard error when behind a reverse proxy. 

'https://host/dashboard/new' will redirect to 'http://host/dashboard/new/',
but no superset service on port 80.

The path '/superset/profile/{username}' has the same issue.

---

Here's how I fixed it:

For /dashboard/new:
```
cd superset-frontend
grep -r 'dashboard/new' src/*
```
Change the found string '/dashboard/new' to '/dashboard/new/' and rebuild the frontend.


For /superset/profile/{username}:
Add '/' after 'f/superset/profile/{user.username}' in superset/views/base.py

It's not elegant but it works.

**Comment by rusackas** [comment]
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening with supported versions of Superset (3.x or newer), just say the word.

**Comment by jdorel** [comment]
Using version 4.1.2 through Helm Chart 0.14.2, this still happens

I'm behind a Traefik Ingress Controller, with `forwardedHeaders` and `proxyProtocols` set to `insecure`
I tried defining `ENABLE_PROXY_FIX`
