### ISSUE TITLE
login page appears after login

### ISSUE THREAD

**Issue by alessiocamillohome** [apache/superset#24685]
HI,
I installed Superset locally using[ Docker Compose instances.](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose) (I get the 2.1 version using the command git checkout 2.1)
I have no errors in the docker compose log when I run **docker-compose -f docker-compose-non-dev.yml up**
```shell
[...]
superset_app          | [2023-07-13 09:40:32 +0000] [8] [INFO] Listening at: http://0.0.0.0:8088 (8)
[...]
``` 

When I try to log-in using http://<my_local_ip>:8088/login the system returns the login page again (credentials are correct).
Maybe I am forgetting some settings. 
Can you help me?
Thanks a lot

Follows my .env-non-dev file:
```shell

COMPOSE_PROJECT_NAME=superset

# database configurations (do not modify)
DATABASE_DB=superset
DATABASE_HOST=db
DATABASE_PASSWORD=superset
DATABASE_USER=superset

# database engine specific environment variables
# change the below if you prefer another database engine
DATABASE_PORT=5432
DATABASE_DIALECT=postgresql
POSTGRES_DB=superset
POSTGRES_USER=superset
POSTGRES_PASSWORD=<my_password>
#MYSQL_DATABASE=superset
#MYSQL_USER=superset
#MYSQL_PASSWORD=superset
#MYSQL_RANDOM_ROOT_PASSWORD=yes

# Add the mapped in /app/pythonpath_docker which allows devs to override stuff
PYTHONPATH=/app/pythonpath:/app/docker/pythonpath_dev
REDIS_HOST=redis
REDIS_PORT=6379

SUPERSET_ENV=production
SUPERSET_LOAD_EXAMPLES=yes
SUPERSET_SECRET_KEY='<my_value>'
CYPRESS_CONFIG=false
SUPERSET_PORT=8088
MAPBOX_API_KEY='<my_value>'

``` 

and superset_config_docker.py file

```shell
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://superset:<my_password>@db/superset"
SQLALCHEMY_ECHO = True

# Flask-WTF flag for CSRF
WTF_CSRF_ENABLED = False
# Add endpoints that need to be exempt from CSRF protection
#WTF_CSRF_EXEMPT_LIST = []
# A CSRF token that expires in 1 year
#WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365

SESSION_COOKIE_HTTPONLY = True  # Prevent cookie from being read by frontend JS?
SESSION_COOKIE_SECURE = False  # Prevent cookie from being transmitted over non-tls?
SESSION_COOKIE_SAMESITE = "None"

# This is for internal use, you can keep http
WEBDRIVER_BASEURL = "http://superset:8088"
# This is the link sent to the recipient. Change to your domain, e.g. https://superset.mydomain.com
WEBDRIVER_BASEURL_USER_FRIENDLY = "http://<my_local_ip>:8088"
```

**Comment by alessiocamillohome** [comment]
I solved by putting x-superset-image: &superset-image apache/superset:2.1.0 in docker-compose-non-dev.yml

**Comment by matheusbsilva** [comment]
If you want a newer version [2.1.1rc1](https://hub.docker.com/layers/apache/superset/2.1.1rc1/images/sha256-3620e302845c02ea991742608481ffd97a43837e0960270a837eea9ab7a3183f?context=explore) also works.

**Comment by alessiocamillohome** [comment]
I need to set the followingg option in connection in Other==> Extra field.

{
  "metadata_params": {},
  "engine_params": {
    "connect_args": {
        "ssl": {
            "mode": "PREFERRED"
        }
    }
  },
  "metadata_cache_timeout": {},
  "schemas_allowed_for_csv_upload": [] 
}

But in the 2.1 version I have two field: 

1. METADATA PARAMETERS 
2. ENGINE PARAMETERS

How can I set my Engine Parameters in the field ENGINE PARAMETERS?
If I set 

```
"connect_args": {
        "ssl": {
            "mode": "PREFERRED"
        }
    }

``` 

I have the following error:

**An error occurred while creating databases: 'str' object does not support item assignment**

**Comment by sebastianliebscher** [comment]
Hi @alessiocamillohome, in order to run Superset 2.1.0 you would also need to run docker-compose with the `TAG` variable:
- `TAG=2.1.0 docker-compose -f docker-compose-non-dev.yml up`

Also, I wouldn't recommend running 2.1.1rc1 in production.

**Comment by Kwazao** [comment]
> * `TAG=2.1.0 docker-compose -f docker-compose-non-dev.yml up`

Hi, I still face the same login problem with V 2.1.0, even after trying multiple configurations with CSRF config / WEBDRIVER URL... Here is my thought process on trying to resolve this issue :

- When i look at the logs it seems to be related to #20319 and the last comment from @sherlock30 implies a missed build in superset-frontend. But I don't see how to fix that inside a running/paused container (npm is not installed in superset_init images). I tried to rebuild images from scratch but it keeps crashing my VM.
- In an other attempt I tried to isolate the issue and the docker image for superset seems to work fine with this very simple config (2.1.1rc1 not to use in prod,):

Debian 10
Superset 2.1.1rc1 (work with 2.1.0 too)

Dockerfile
```Dockerfile
FROM apache/superset:2.1.1rc1
# passing SECRET_KEY for docker-compose use
ARG SUPERSET_SECRET_KEY
ENV SUPERSET_SECRET_KEY=$SUPERSET_SECRET_KEY

# Switching to root to install the required packages
USER root
# as suggested in the dockerhub doc
RUN pip install mysqlclient
RUN pip install psycopg2
RUN pip install sqlalchemy

# Switching back to using the `superset` user
USER superset
RUN superset fab create-admin \
--username admin \
--firstname Superset \
--lastname Admin \
--email admin@superset.com \
--password <youradminpassword>

RUN superset db upgrade
RUN superset init
RUN superset load_examples
WORKDIR /app
CMD ["/bin/sh","-c","/usr/bin/run-server.sh"]
```

docker-compose.yml
``` YAML
x-superset-depends-on: &superset-depends-on
  - db
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  db:
    env_file: .env
    image: postgres:14
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    build:
      context: .
      args: 
        SUPERSET_SECRET_KEY: '<secret-key>'
      dockerfile: Dockerfile
    container_name: superset_app
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

volumes:
  superset_home:
    external: false
  db_home:
    external: false
```

So, right know I don't know if there is a hope for this issue to be fixed and have a decent production stack or if I need to rebuild myself a complete docker-compose.yml, step-by-step... 

Any thoughts ?

**Comment by alessiocamillohome** [comment]
> Hi @alessiocamillohome, in order to run Superset 2.1.0 you would also need to run docker-compose with the `TAG` variable:
> 
> * `TAG=2.1.0 docker-compose -f docker-compose-non-dev.yml up`
> 
> Also, I wouldn't recommend running 2.1.1rc1 in production.

I am using version 2.1.0 in production. 
What is the latest stable version that I can use in production?

**Comment by sebastianliebscher** [comment]
@alessiocamillohome latest stable is 2.1.0

@Kwazao maybe your issue is the same as https://github.com/apache/superset/discussions/24581#discussioncomment-6426217

**Comment by alessiocamillohome** [comment]
thanks @sebastianliebscher.
Maybe you can help me with a small problem.
I lose the "Save" button when I am in Dashboard editing with user admin (admin role)
I'm using the 2.1.0 version.
How can I fix this? 

Thanks a lot,
Alessio

**Comment by alessiocamillohome** [comment]
> thanks @sebastianliebscher. Maybe you can help me with a small problem. I lose the "Save" button when I am in Dashboard editing with user admin (admin role) I'm using the 2.1.0 version. How can I fix this?
> 
> Thanks a lot, Alessio

I solved this issue by deleting the database volume and recreating it. 
Maybe there was something left in the db from the latest version I was using before. (I went from the latest to 2.1.0).

**Comment by lehug** [comment]
same issue.localhost works,but ip can not

**Comment by koasi** [comment]
same issue here, I'm using docker image(Letest), 
if run by http://localhost:8080 then can login success. but if using ip like http://192.168.1.X.:8080 after click login will get back to login page, and check http status get a 302 error

**Comment by koasi** [comment]
it's resloved when i set  TALISMAN_ENABLED = FALSE, it could access via 192.168.1.X
![image](https://github.com/apache/superset/assets/76172989/c5e5c3af-78f9-4b12-a665-9ffa6f2c06ab)

**Comment by Kwazao** [comment]
> it's resloved when i set TALISMAN_ENABLED = FALSE, it could access via 192.168.1.X ![image](https://user-images.githubusercontent.com/76172989/255344776-c5e5c3af-78f9-4b12-a665-9ffa6f2c06ab.png)

This is the solution that worked for me, thanks.

**Comment by sfirke** [comment]
Closing as a duplicate of https://github.com/apache/superset/issues/24685

**Comment by zajcomm** [comment]
Ok so this fixed it for me 🐅. please let me know if it works for you .
Accessing http://localhost:8088 after setting up Apache Superset with Docker returned a 404 error for loading.gif and the page appeared without CSS.
The solution that worked for me was to **Rebuild the Docker images and restart the containers:**
- Stop the running Docker containers:  `docker-compose down`
- Navigate to the superset directory. `cd superset` my default.
- Rebuild and start the containers: `docker-compose up --build`  # simply adding the `--bulid` to the previous way.
thats it. you can check Docker logs for any error messages: docker-compose logs.
------------------

One thing I noticed however, i got some other warnings  in the logs during the build process. For example, warnings in the superset_node container logs related to missing modules or export not found, such as:
```
WARNING in ./node_modules/@data-ui/shared/esm/enhancer/WithTooltip.js 3:60-78
export 'withTooltipPropTypes' (imported as 'vxTooltipPropTypes') was not found in '@vx/tooltip/build/tooltips/TooltipWithBounds' (possible exports: __esModule, default)

```
and
```
WARNING in ./src/utils/textUtils.ts 21:11-44
Module not found: Error: Can't resolve '../../../superset_text' in '/app/superset-frontend/src/utils'

```
These warnings indicate that there are missing dependencies or incorrectly referenced modules in the code. While these warnings might not cause the application to fail, they should be addressed to ensure the application works as expected.
