### ISSUE TITLE
Data preview for trino tables does not work for all trino connection types

### ISSUE THREAD

**Issue by jshumway-zs** [apache/superset#25307]
Data preview for trino tables does not work for all trino connectors (specifically for iceberg in our case). This issue results because the response from "select * from table$partitions" is dependent on the connection type (this is used in superset/db_engine_specs/presto.py). It seems that the code  was written based off of the response for a [hive](https://trino.io/docs/current/connector/hive.html#partitions-table) connection, but the response schema is different for other connection types (see the iceberg docs [here](https://trino.io/docs/current/connector/iceberg.html#partitions-table) for example). 

#### How to reproduce the bug

1. create an iceberg table in trino
2. perform an action which will trigger a table preview on the table (such as selecting the table from the dropdowns in sqllab)
3. you will see an error such as "column 'partition' cannot be resolved"

### Expected results

The preview should run properly and display the data preview

### Actual results

The preview fails and an error message is shown

#### Screenshots

![image](https://github.com/apache/superset/assets/137825176/4ca9b3af-5eb8-4b2c-afea-6d648e8e6d22)

### Environment

(please complete the following information):

- superset version: 2.1.1

### Additional context

I have fixed this on our end by checking if the returned partition columns match the schema described in the iceberg documentation and if so, I return None. However this doesn't allow us to see the most recent partition and is also specific to iceberg. I would recommend setting latest_partition to False in the select_star method for trino until a better solution is found, as selecting from the most recent partition isn't critical in most cases.

**Comment by OmarSultan85** [comment]
Hello, I am facing the same issue, were you able to resolve this?

**Comment by jshumway-zs** [comment]
> Hello, I am facing the same issue, were you able to resolve this?

Hey @OmarSultan85, for now we have just forked and removed the most recent partition logic as it isn't critical for us. I've found that it also affects bigquery tables accessed through trino and is still an issue in version 3.0.0 as well.

**Comment by amir-bashir** [comment]
@jshumway-zs 
Can you please share which files need to be modified and which function to be removed to make it work. 
In my case superset 3.0 is adding record_count, and file_count to where clause for every iceberg table.
What it does is read the metadata information from partition file and then use values from this file to append as where clause. 
![image](https://github.com/apache/superset/assets/121928193/b680b232-dbac-4556-9e97-f09fa794b189)

**Comment by jshumway-zs** [comment]
> @jshumway-zs Can you please share which files need to be modified and which function to be removed to make it work. In my case superset 3.0 is adding record_count, and file_count to where clause for every iceberg table. What it does is read the metadata information from partition file and then use values from this file to append as where clause.

Here is a snippet from our dockerfile which we are using to correct. Basically we return early in presto.py on line 524 and then remove lines 73-92 in trino.py. Obviously the line numbers will depend on the release. Its been a while since I looked at this, so I'm not sure which methods are being modified here, but if you look a the code from the 3.0.0 branch you should get an idea.

```
FROM apache/superset:3.0.0rc4

USER root

RUN sed -i "524i \        return None" /app/superset/db_engine_specs/presto.py
RUN sed -i 73,92d /app/superset/db_engine_specs/trino.py

USER superset
```

**Comment by jkleinkauff** [comment]
+1 we are facing the same issue here. Superset 3.1.1 and Iceberg tables in Trino.

**Comment by rusackas** [comment]
Pinging some users/SMEs from the [rolodex](https://docs.google.com/spreadsheets/d/1U1qxiLvOX0kBTUGME1AHHi6Ywel6ECF8xk_Qy-V9R8c/edit#gid=0) on this one, since a solution might actually close TWO issues:
@john-bodley
@sujiplr
@nytai

**Comment by zspsole** [comment]
This is still the case on latest release (4.0.1). As described by @jshumway-zs, the Trino db engine extends from the Presto one, that has the method `where_latest_partition` defined that the preview fuction uses to make sure you only preview data from the latest partition.

This method adds a WHERE clause using all the columns/values from the <table_name>$partitions first entry. This doesn't work in Trino. If it's not fixed at least it could be removed by overriding the method to the default implementation (`return None`).

**Comment by jack-o-hara** [comment]
Agree this is painful for my users. We also have Iceberg tables which have extremely large metadata files (100s of cols + big tables + partitioning) so running $partitions is quite slow (5-15 secs) and col schema loading on the UI is delayed until it completes. 

Also agree the info returned is somewhat useless. Our users just need some indication that a column in the schema is used as a partition.

**Comment by rusackas** [comment]
Anyone still facing this and/or willing to look into it? It's been silent for >200 days, so it's at risk of being closed as stale/not-planned.

**Comment by ghub-ty0** [comment]
> Anyone still facing this and/or willing to look into it? It's been silent for >200 days, so it's at risk of being closed as stale/not-planned.

We just updated to version 4.1.1 where this is still an issue while using Trino version 474.

**Comment by nferrario** [comment]
Same issue with Superset 5.0.0rc3 and Trino 476. I tested tables with `identity` and `day` partitions, no difference.


```
latest partition: data=[[701926, 1382594, 0, null], [5107476, 13853133, 0, null], [3, 4425, 0, null], [1067122, 2206765, 0, null], [7102964, 11962808, 0, null], [-1, 491016, 0, null], [-1, 491016, 0, null], [3, 888, 0, null], [2308931, 4232943, 0, null], [1, 682480, 41, null], [9.520000000000001e-07, 586.3125134255419, 41, null], [3.9999999329447746e-05, 620.4365139340313, 41, null], [5.4000450782310966e-05, 682.4801653274344, 41, null], [9.520000000000001e-07, 498.1414695199912, 41, null], [9.520000000000001e-07, 498.1414695199912, 41, null] ...
```

**Comment by jkleinkauff** [comment]
Folks, running 5.0.0 and this is still happening.

**Comment by ghost** [comment]
6.1.0 with Trino 481 still has this issue.

**Comment by malon64** [comment]
Still having this problem on Superset 6.1.0.  I'm proposing a PR to fix this problem one for all, I'll be happy if someone on the team could review it
