### ISSUE TITLE
Error importing dashboard

### ISSUE THREAD

**Issue by ruifpedro** [apache/superset#27027]
### Bug description

Hey Superset team!

Since I've upgraded from Superset v3.0.0 to v3.1.0, I have stopped being able to successfully import dashboards that contain datasets that specifically use a Trino datasource, with the new feature of `Enable row expansion in schemas` enabled.
Additionally figured out that if I modify the respective database yaml that is shipped out in the zip export, and manually remove the `extra.schema_options.expand_rows` key and value, importing works. This mitigates the problem for the time being, but does not solve it.

The source of the problem seems to lie in the Superset importing tool not take into account this new Trino feature.

I will provide evidence and more context below.

Looking forward your response and happy to clarify any more details.

### How to reproduce the bug

1. Go to Dashboards
2. Bulk select dashboards that contain charts that use a Trino database with `Enable row expansion in schemas`  enabled
3. Export dashboards
4. Import dashboards

### Screenshots/recordings

Superset stacktrace:
```
Command failed validation
2024-02-06 10:56:35,825:INFO:superset.commands.dashboard.importers.dispatcher:Command failed validation
CommandException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1454, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 108, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/dashboards/api.py", line 1193, in import_
    command.run()
  File "/app/superset/commands/dashboard/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/commands/dashboard/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 73, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 111, in validate
    raise CommandInvalidError(
superset.commands.exceptions.CommandInvalidError: Error importing dashboard
2024-02-06 10:56:35,826:WARNING:superset.views.base:CommandException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_appbuilder/security/decorators.py", line 95, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 127, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 121, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1454, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 255, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/base_api.py", line 108, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/dashboards/api.py", line 1193, in import_
    command.run()
  File "/app/superset/commands/dashboard/importers/dispatcher.py", line 64, in run
    raise exc
  File "/app/superset/commands/dashboard/importers/dispatcher.py", line 57, in run
    command.run()
  File "/app/superset/commands/importers/v1/__init__.py", line 73, in run
    self.validate()
  File "/app/superset/commands/importers/v1/__init__.py", line 111, in validate
    raise CommandInvalidError(
superset.commands.exceptions.CommandInvalidError: Error importing dashboard
```

# Screenshots
Superset error
![Screenshot_20240206_110928](https://github.com/apache/superset/assets/13442135/a6da5de2-8caa-4aa9-97de-ef0b599bc46f)

Browser debug
![Screenshot_20240206_111352](https://github.com/apache/superset/assets/13442135/05b594fd-017c-4417-813f-a8134e8d6418)

Trino Database connection
![Screenshot_20240206_110907](https://github.com/apache/superset/assets/13442135/d9b4bcc2-7e6e-4dcd-88d3-5f1a7509a10e)

Trino Database exported YAML
![Screenshot_20240206_111702](https://github.com/apache/superset/assets/13442135/0ecec2b6-25f1-4486-b28b-cba148e5d88d)

### Superset version

3.1.0

### Python version

3.9

### Node version

Not applicable

### Browser

Firefox

### Additional context

I have the following feature flags enabled:
```
FEATURE_FLAGS = {
      "ALERT_REPORTS": True,
      "DASHBOARD_RBAC": True,
      "ENABLE_TEMPLATE_PROCESSING": True,
    }
```

There are no customization made on Superset, but the container image is packaged by me in order to include necessary dependencies like the Trino connector.
The Superset is deployed in Kubernetes using the official Superset helm chart.

About the data source I am querying, I've already provided details on it on the post.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Nice issue description @ruifpedro! Thank you.

I'll tag some folks with knowledge about that feature: @betodealmeida @eschutho @rusackas

**Comment by ilndinesh** [comment]
Hello @ruifpedro thank you for detailed explanation. It helped us as well.

**Comment by lokeshwar9** [comment]
Hello @ruifpedro , Your detailed explanation helped us figure out that checking the "enable row expansion" is causing the dashboard import error in the same instance and different instance,  we fixed it by writing code to stop schema options keys from going into the export zip.
we noticed that we are unable to uncheck the "enable row expansion"  using GUI and we used curl to uncheck it.
Many Thanks once again and hope this helps others as well.
Good day

**Comment by marituhone** [comment]
@ruifpedro do you manage to solve the issue,i get the same issue how can i fix it?

**Comment by ruifpedro** [comment]
> Hello @ruifpedro , Your detailed explanation helped us figure out that checking the "enable row expansion" is causing the dashboard import error in the same instance and different instance, we fixed it by writing code to stop schema options keys from going into the export zip. we noticed that we are unable to uncheck the "enable row expansion" using GUI and we used curl to uncheck it. Many Thanks once again and hope this helps others as well. Good day

I've missed your comment! Yes that it's the case, I'm also unable to uncheck the "enable row expansion" option.

**Comment by ruifpedro** [comment]
> @ruifpedro do you manage to solve the issue?i get the same issue how can i fix it?

As my first post states, I've managed to circumvent the problem by simply, exporting the dashboard, opening up the zip and modifying the respective database yaml to manually remove the `extra.schema_options` key and values. Zip the contents and then you have a valid set of assets that can be imported.

**Comment by JustGui** [comment]
Hey guys ! It's still an issue on 4.0.2; is a fix planned for it ?

**Comment by rusackas** [comment]
> Hey guys ! It's still an issue on 4.0.2; is a fix planned for it ?

Welcomed, yes, but planned... not so much. Unless @yousoph is aware of this and planning to get it in a Preset sprint, I doubt we'll see a fix soon. Contributions/PRs more than welcomed if you'd like to tackle this one!

**Comment by SuDaYu2019** [comment]
我也遇到这个问题（4.1.1）。在数据集设置里，添加过参数模板（jinja）。  导致产生了template_params。   从而影响到了看板和数据库的导入（导出并没有影响）。

![Image](https://github.com/user-attachments/assets/53447af1-2e4b-4583-a2c3-c6cab947f46b)

**Comment by eschutho** [comment]
@geido can we put up a bounty for this?

**Comment by qleroy** [comment]
This is a fix https://github.com/apache/superset/pull/32657 ?

**Comment by rusackas** [comment]
Can anyone cofirm or deny if https://github.com/apache/superset/pull/32657 resolved this?

**Comment by rusackas** [comment]
Or https://github.com/apache/superset/pull/33547 for that matter (you'd have to pull it and test locally)

**Comment by amirhosseinkabiri** [comment]
read this article. it may help
https://medium.com/@amirhosseikabiri/solving-the-superset-import-export-issue-a-step-by-step-guide-35f16451b196

**Comment by rusackas** [comment]
PR #32657 ("fix(import): Import a DB connection with expanded rows enabled") was merged on 2025-03-14 and should address this issue — it specifically fixes importing database connections that have the "Enable row expansion in schemas" (Trino `schema_options`) feature enabled. If you're still seeing import failures with Trino datasources on a version that includes that fix, it would be great if you could open a new issue with your Superset version and error details. Closing as fixed — last activity was approximately 7 months ago.
