### ISSUE TITLE
A space is missing for the "+ SQL Query" button

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#32773]
## Screenshot

![Image](https://github.com/user-attachments/assets/c401c867-d178-4ce7-b156-a96415d38c97)

## Description

On Welcome screen, a space is missing for the "+ SQL Query" button
Others buttons are OK

**Comment by xavier-GitHub76** [comment]
Version : Superset 4.1.1

**Comment by rusackas** [comment]
It looks like there is a space on the second one... not sure what you mean with that.

**Comment by rusackas** [comment]
Same issue with this cached display in the Chart Editor

<img width="305" alt="Image" src="https://github.com/user-attachments/assets/02d5abad-de3e-4b2b-b540-ee3eeab3a087" />

**Comment by mistercrunch** [comment]
Doing quite a bit or refactoring around antd v5 migration, we'll likely get to those but could use some help. Should be easy to `git grep -i "+SQL Query` and submit a fix.

**Comment by xavier-GitHub76** [comment]
@rusackas : 
> It looks like there is a space on the second one... not sure what you mean with that.

There appears to be a space, but it's narrower than the other buttons.
Unsure, I compared it with screenshots.

![Image](https://github.com/user-attachments/assets/6abf17f6-ea68-4f8d-93e6-c696b47493a2)

**Comment by mistercrunch** [comment]
> cached display in the Chart Editor

@rusackas this is fixed in the `template_less` (Theming) collab branch, looking to merge into `master` once 5.0 is done, and will be the basis for 5.1.x

**Comment by abhinav-1305** [comment]
Hi @rusackas - is this resolved?

**Comment by mistercrunch** [comment]
@abhinav-1305 you should be able to pull the `5.0.0rc4` and check whether it's there or not, but if not someone could potentially patch for 5.1 . On our side focussing on 6.0 where this and hundreds of other visual glitches are already addressed.

**Comment by xavier-GitHub76** [comment]
I try with 5.0.0rc4 but space is missing

![Image](https://github.com/user-attachments/assets/6af64065-23a5-484a-a661-a5b31619a6fd)

![Image](https://github.com/user-attachments/assets/b8253f19-fff1-41f2-9102-8a085bc891fc)

![Image](https://github.com/user-attachments/assets/d266698f-fec7-49f4-8d09-657cfd12f9d5)

**Comment by mistercrunch** [comment]
Ok, if someone wants to fix it in theory we can flag the PR to get cherried into 5.0.1 or 5.1.0, whichever comes first. Otherwise it'll be in 6.0. There will be a big push to make 6.0 look squeaky clean, most effort will be put in that direction along with all the theming-related features.

**Comment by xavier-GitHub76** [comment]
I don't know if it can make a difference, but my test was conducted using the Docker image 5.0.0rc4.
I just discovered GitHub's ephemeral environments (very handy) for testing the PR https://github.com/apache/superset/pull/33762

The space is correct on http://44.247.50.122:8080/

![Image](https://github.com/user-attachments/assets/852f1d02-5f5a-4993-a96c-5164014d8757)

However, the image 5.0.0rc4 is more recent (Jun 18, 2025 at 7:45 pm) than the commit fb9869710dc32669e1012ccf01c62db252d54849 (Jun 12, 2025)

**Comment by msyavuz** [comment]
Reopening this as the specific SQL Query button is still present after #34237

**Comment by EnxDev** [comment]
I see this on the homepage 

<img width="1593" height="356" alt="Image" src="https://github.com/user-attachments/assets/5cbb5c63-6e99-4b01-8674-46f818d2c7fd" />

**Comment by msyavuz** [comment]
Oh yeah it's fixed. I was not on master
