### ISSUE TITLE
Superset 5.0.0: charts cannot be displayed with Pinot DB (incorrect SQL dialect used)

### ISSUE THREAD

**Issue by NickTick92** [apache/superset#34700]
### Bug description

Hello, I'm using Superset in 5.0.0 and can't create charts with Apache Pinot as datasource anymore. Looks like the chart tool isn't using the correct SQLGLOT? The charts are using the dialect with backticks and schema instead without. I'm using a Postgres as meta database. I can't find anything mentioned in docs about this.

1. Install `pinotdb` connector in image -> [Apache Pinot Configuration Doc](https://superset.apache.org/docs/configuration/databases#apache-pinot)
2. Create database connection in Superset UI
3. Add a Pinot datasource
4. Try to create a raw table from this valid data source
5. Inspect Query in SQLAlchemy and see that its using backticks and not without

Do I need to install or configure anything else so that it recognizes the dialect correctly?
Thank you!

### Screenshots/recordings

**Valid Datasource Overview:**

<img width="686" height="567" alt="Image" src="https://github.com/user-attachments/assets/7efdaa75-80ef-4c3c-875f-b4f1888bbd5d" />

**Error during chart building:**

<img width="1752" height="542" alt="Image" src="https://github.com/user-attachments/assets/27756341-f737-4145-949f-b80f8ec6699a" />

**Faulty Query:**

<img width="554" height="284" alt="Image" src="https://github.com/user-attachments/assets/b5abb905-0f50-48cb-a7eb-f7541f7f8fc5" />

**Expected Query:**

<img width="1540" height="773" alt="Image" src="https://github.com/user-attachments/assets/d04a836d-1ebf-4a85-9dfd-01ee71406e26" />

### Superset version

5.0.0

### Python version

3.11

### Node version

I don't know

### Browser

Chrome

### Additional context

```bash
FROM <OUR_OWN_EXTENDED_IMAGE>/superset:5.0.0 # Own Image built with BUILD_TRANSLATIONS=true

USER root

ENV PYTHONPATH /app/pythonpath
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

RUN . /app/.venv/bin/activate && \
    uv pip install \
    redis \
    psycopg2-binary \
    pinotdb \
    Pillow

COPY --chown=superset config/superset/superset_config.py /app/
COPY --chown=superset config/superset/assets/logo.svg /app/.venv/lib/python3.11/site-packages/superset/static/assets/images/logo.svg

USER superset

CMD ["/app/docker/entrypoints/run-server.sh"]
```

```python
# superset_config.py
# ... other configs

SQLALCHEMY_DATABASE_URI="postgresql://superset:superset@superset-db:5432/superset" # Meta-Database
```

Database URI via Superset: `pinot://pinot-broker:8099/query/sql?controller=http://pinot-controller:9000/`

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by betodealmeida** [comment]
This is fixed in `master` (https://github.com/apache/superset/pull/33848) and should be easy to fix in your installation manually:

```diff
diff --git a/superset/sql/parse.py b/superset/sql/parse.py
index f2fd5474b5..0d53d47d51 100644
--- a/superset/sql/parse.py
+++ b/superset/sql/parse.py
@@ -85,7 +85,7 @@ SQLGLOT_DIALECTS = {
     # "odelasticsearch": ???
     "oracle": Dialects.ORACLE,
     "parseable": Dialects.POSTGRES,
-    # "pinot": ???
+    "pinot": Dialects.MYSQL,
     "postgresql": Dialects.POSTGRES,
     "presto": Dialects.PRESTO,
     "pydoris": Dialects.DORIS,
```

**Comment by betodealmeida** [comment]
Feel free to reopen if this doesn't work! Thanks! :)

**Comment by NickTick92** [comment]
Hello @betodealmeida and thank you for your input :) Seems like I don't have the permissions to reopen this issue.

I've been trying a few things over the last few days and following the other issues here, but so far without success.
Both the `5.0.0` tag and the `6.0.0rc1` & `6.0.0rc2` tags still have the problem of setting the ticks and schema in the query. 

```dockerfile
FROM apache/superset:6.0.0rc2
USER root

ENV PYTHONPATH /app/pythonpath
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

RUN . /app/.venv/bin/activate && \
    uv pip install \
    redis \
    psycopg2-binary \
    pinotdb \
```
I've tried the suggested hacks like https://github.com/apache/superset/issues/34856#issuecomment-3225455138 but without success. How does the parser work? Do I need to execute any commands afterwards for the change to be recognized?

<img width="1124" height="536" alt="Image" src="https://github.com/user-attachments/assets/03a14d9a-200a-4911-90fb-a41c4846cbe8" />
