### ISSUE TITLE
[BUG]: Sort By on table viz produces undesired results.

### ISSUE THREAD

**Issue by mmuru** [apache/superset#9620]
Sort By on table viz produces undesired results.
### Expected results
It should able to sort the result set.
### Actual results
Adding an extra column in the result set - which is confusing. 
#### Screenshots
![image](https://user-images.githubusercontent.com/11397834/80009779-5f6dd280-847e-11ea-82d7-5bf7fd2d874e.png)
![image](https://user-images.githubusercontent.com/11397834/80009881-84624580-847e-11ea-8660-234d11c0b446.png)
![image](https://user-images.githubusercontent.com/11397834/80010006-a3f96e00-847e-11ea-9c18-fb7487daf7fc.png)
#### How to reproduce the bug
1. Go to source->tables->select bart_lines
2. Click on bart_lines to explore data set
3. Scroll down to "Sort By"  (choose a column or aggregate function). Unable to select the Group by columns (see the screen shot). It forces to select aggregate function or custom sql otherwise it throws duplicate columns exception if custom sql column doesn't have alias name.
See attached screen shot (result window)
### Environment

(please complete the following information):

- superset version:  0.36.0, 0.35.2 and the master 
- python version: 3.6.8
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
The explore request 
`http://localhost:8088/superset/explore/?form_data={"datasource":"13__table","viz_type":"table","url_params":{},"time_range_endpoints":["inclusive","exclusive"],"granularity_sqla":null,"time_grain_sqla":"P1D","time_range":"Last+week","groupby":["name"],"metrics":[{"expressionType":"SIMPLE","column":{"id":456,"column_name":"color","verbose_name":null,"description":null,"expression":null,"filterable":true,"groupby":true,"is_dttm":false,"type":"VARCHAR(255)","optionName":"_col_color"},"aggregate":"COUNT","sqlExpression":null,"hasCustomLabel":false,"fromFormData":true,"label":"COUNT(color)","optionName":"metric_qqaak8p1tnh_c7yss63hqv7"}],"percent_metrics":[],"timeseries_limit_metric":{"expressionType":"SIMPLE","column":{"id":455,"column_name":"name","verbose_name":null,"description":null,"expression":null,"filterable":true,"groupby":true,"is_dttm":false,"type":"VARCHAR(255)","optionName":"_col_name"},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"hasCustomLabel":false,"fromFormData":false,"label":"COUNT_DISTINCT(name)","optionName":"metric_r322b0kf66c_hctq4pk133v"},"row_limit":10000,"include_time":false,"order_desc":true,"all_columns":[],"order_by_cols":[],"adhoc_filters":[],"table_timestamp_format":"%Y-%m-%d+%H:%M:%S","page_length":0,"include_search":false,"table_filter":false,"align_pn":false,"color_pn":true,"show_cell_bars":true}`

the query:
`SELECT name AS name,
       count(color) AS "COUNT(color)",
       **count(DISTINCT name) AS "COUNT_DISTINCT(name)"**
FROM bart_lines
GROUP BY name
ORDER BY "COUNT_DISTINCT(name)" DESC
LIMIT 10000;`

To explore table viz, it should not force to select metrics aggregation instead it should provide columns to be selectable. I noticed the explore request "metrics" key in form_data includes "Sort By" value and it should not add it to the list. The "order_by" key has already the same value. Before, I submit the PR for this issue, need to understand the intend of "sort_by" for Table viz. Please, provide the context.

**Comment by mmuru** [comment]
@villebro: Please, can you review this issue and provide your feedback?

**Comment by villebro** [comment]
I believe this is a problem in the way table viz is currently implemented, and getting this functionality into the current sorting control can be difficult. The table viz is currently undergoing some refactoring, and I'll try to keep this in mind to make sure it is addressed when the time is right.

**Comment by rea725** [comment]
** Expected Result addendum **
- "Sort By" parameter should be basis for sort, but not basis for display.
- Chart can be configured to sort by a column that is not the last (right-most) column in the table.
- If the column being sorted upon is a metric with a d3 number format specified, the number format should be applied.

**Current Behavior**
- Including a column as a "Sort By" parameter will cause it to be displayed.
- The column will be displayed without its intended d3 number format.

**Comment by RageAgainstTheMachine101** [comment]
> I believe this is a problem in the way table viz is currently implemented, and getting this functionality into the current sorting control can be difficult. The table viz is currently undergoing some refactoring, and I'll try to keep this in mind to make sure it is addressed when the time is right.

Hello, @villebro!
Do you have some news about this bug?
Is there some patches witch can fix this?

**Comment by ktmud** [comment]
@RageAgainstTheMachine101 I think this is already fixed in the latest branch.

**Comment by ktmud** [comment]
@RageAgainstTheMachine101 I think the issue with `sort by` being automatically added to display has already been fixed.

**Comment by ktmud** [comment]
Pin the issue to track the progress on allowing GROUP BY columns in sorting.

**Comment by mmuru** [comment]
@villebro: I tested it with latest version 1.0 and sort_by issue is still exist. Although it is still forced to select aggregate function  for sort_by column but it did not get included in the result. 
`SELECT name AS name,
       count(color) AS "COUNT(color)",
       count(name) AS "COUNT(name)"
FROM public.bart_lines
GROUP BY name
ORDER BY "COUNT(name)" ASC
LIMIT 10000;`

Noticed the following issue: In the custom SQL, changing column name as name2 the following query generated and throws exception.
`SELECT name AS name,
       count(color) AS "COUNT(color)",
       name as name2 AS "name as name2"
FROM public.bart_lines
GROUP BY name
ORDER BY "name as name2" DESC
LIMIT 10000;`

`Traceback (most recent call last):
  File "/Users/muru/venv367/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 1274, in query
    df = self.database.get_df(sql, self.schema, mutator)
  File "/Users/muru/venv367/lib/python3.6/site-packages/superset/models/core.py", line 390, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/Users/muru/venv367/lib/python3.6/site-packages/superset/db_engine_specs/base.py", line 877, in execute
    cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "AS"
LINE 3:        name as name2 AS "name as name2"`

**Comment by rusackas** [comment]
This no longer appears to be the case in current/supported versions of Superset (e.g. 2.0.1). Closing as done, but perhaps we can re-open with updated screenshots/context if there's a lingering issue.
